#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

CONFIG="install.conf.yaml"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTBOT="$BASEDIR/dotbot/bin/dotbot"

# XXX want to automatically handle setting up Gem and Ruby ctags:
# - see https://thoughtbot.com/upcase/videos/intelligent-navigation-with-ctags
#
# - https://github.com/tpope/rbenv-ctags and things linked from there
# mkdir -p ~/.rbenv/plugins
# git clone git://github.com/tpope/rbenv-ctags.git \
  # ~/.rbenv/plugins/rbenv-ctags
# rbenv ctags
#
# - https://github.com/tpope/gem-ctags
# gem install gem-ctags
# gem ctags


main() {
    cd "${BASEDIR}"

    header 'Installing dependencies'
    install_dependencies

    header 'Installing dotfiles'
    bin/faketty "$DOTBOT" -d "${BASEDIR}" -c "${CONFIG}" "${@}" | indent

    # Copy example private environment variable file (if needed), so these can be
    # set but not committed.
    if [ ! -f zsh/env.private.sh ]; then
        header 'Copying private environment variables file'
        cp zsh/env.private.{example.,}sh
    fi

    header 'Setting up Vim'
    mkdir -p vim/{session,undodir,view}
    vim +':PlugInstall | :PlugUpdate | :qa!'

    header 'Setting up Tmux'
    ~/.tmux/plugins/tpm/bin/install_plugins

    header 'Linking other needed files'
    link_files

    header 'Enabling services'
    enable_services
}

install_dependencies() {
    local package_manager

    git submodule update --init --recursive

    for package_manager in pacman yaourt; do
        xargs sudo "$package_manager" -S --noconfirm --needed < dependencies/"$package_manager"
    done

    yarn global add elm@0.19 elm-format@exp create-elm-app elm-oracle elm-test
}

link_files() {
    # XXX Move doing all this into `install.conf.yaml`?

    set +u
    # shellcheck disable=SC1091
    source 'zsh/env.sh'
    set -u

    ln -sf "$DROP"/.aws ~/.aws
    ln -sf "$DROP"/.ssh/ ~/.ssh
    ln -sf "$DROP"/vim/spell/ ~/.vim/spell

    mkdir -p ~/.todo/
    ln -sf "$NOTES"/todo/done.todo ~/.todo
    ln -sf "$NOTES"/todo/next_actions.todo ~/.todo
    ln -sf "$NOTES"/todo/report.todo ~/.todo
    ln -sf "$DOTFILES"/zsh/lib/todotxt.sh ~/.todo/config

    # Link files in to `/etc`; cannot occur via `dotbot` as this doesn't
    # support linking as root (see
    # https://github.com/anishathalye/dotbot/issues/125).
    sudo ln -sf "$DOTFILES"/etc/udevmon.yaml /etc/
}

enable_services() {
    sudo systemctl enable --now udevmon
}

header() {
    echo
    # shellcheck disable=SC2001
    echo "$@" | sed 's/^/======> /'
    echo
}

indent() {
    sed 's/^/       /'
}

main "$@"
