# Config for https://github.com/clearloop/leetcode-cli.
# To use CLI:
# - Sign in in Firefox and set env vars - see below; first time on each machine
# only.
# - `leetcode list` to choose
# - `leetcode edit 3` to start
# - `leetcode test 3` to test
# - `leetcode exec 3` to submit

[code]
editor = 'vimx'
edit_code_marker = false
start_marker = ""
end_marker = ""
comment_problem_desc = true
test = true

# Uncomment as applicable for language to use:

# For Python.
lang = 'python3'
comment_leading = "#"

# For TypeScript.
# lang = 'typescript'
# comment_leading = "//"

# For Go.
# lang = 'golang'
# comment_leading = "//"

[cookies]
# `LEETCODE_SESSION` and `LEETCODE_CSRF` need to be set in
# `$DOTFILES/zsh/env.private.sh`, as described in
# https://github.com/clearloop/leetcode-cli#cookies. Sign in in Firefox and
# grab these values from Storage tab.
# `LEETCODE_CSRF` = value of `csrftoken` item.
# `LEETCODE_SESSION` = value of `LEETCODE_SESSION` item.
session = ''
csrf = ''
site = "leetcode.com"

[storage]
# XXX BW 2025-11-22: Doesn't seem to actually do anything?
cache = 'cache'
code = 'solutions'
root = '~/src/github.com/bobwhitelock/dsa/src/leetcode'
scripts = 'scripts'
