version: '3'

tasks:
  dev:
    desc: Install development dependencies
    cmds:
      - pipx install pre-commit vint

  # TODO BW 2026-01-26: Add install and other scripts in here instead? Though
  # then need `task` installed first.

  lint:
    desc: Run all linters
    cmds:
      - pre-commit run --all-files

  check:zsh:
    desc: Check zsh files for syntax errors
    cmds:
      - for f in zsh/*.sh zsh/lib/*.sh; do echo "Checking $f..."; zsh -n "$f"; done

  ci:
    desc: Full CI pipeline
    cmds:
      - task: lint
      - task: check:zsh
