
# Note: need to run `sync` for this session to be available.

<%
require "json"

abort "Usage: mux start project PATH" unless @args.size == 1 && File.exist?(@args[0])

project_path = File.expand_path(@args[0])
project_owner = File.basename(File.dirname(project_path))
project_name = File.basename(project_path)

project_specific_setup = \
  if File.exist?("#{project_path}/package-lock.json")
    {npm: ["npm install", "npm start"]}
  elsif File.exist?("#{project_path}/Makefile")
    # TODO BW 2025-09-03: This doesn't work for `rescale-platform-web` as that
    # now has a Makefile, but the default command isn't the main task for the
    # project.
    ["make"]
  else
    nil
  end.to_json
%>

name: <%= [project_owner, project_name].join('/') %>
startup_window: <%= project_name %>
# XXX Don't reprompt for this when it's already added.
on_project_start: ssh-add ~/.ssh/id_rsa.bob

windows:
  - notes:
      root: <%= ENV.fetch('NOTES') %>
      layout: even-horizontal
      panes:
        - gpl
        - vim 'stream.md'

  - <%= project_name %>:
      layout: '6827,274x73,0,0{136x73,0,0[136x36,0,0,41,136x36,0,37,50],137x73,137,0,47}'
      root: <%= project_path %>
      panes:
        - <%= project_specific_setup %>
        # XXX Add ability to have custom per-project config here, which can
        # also be specified in dotfiles-private as well - and can then resolve
        # https://github.com/bobwhitelock/dotfiles-private/issues/2.
        -
        - vim

  - dotfiles:
      root: <%= ENV.fetch('DOTFILES') %>
      layout: even-horizontal
      panes:
        - gpl
        - vim
