
# Note: need to run `sync` for this session to be available.

<%
require "json"

abort "Usage: mux start project PATH" unless @args.size == 1 && File.exist?(@args[0])

project_path = File.expand_path(@args[0])
project_name = File.basename(project_path)

project_specific_setup = \
  if File.exist?("#{project_path}/package-lock.json")
    {npm: ["npm install", "npm start"]}
  elsif File.exist?("#{project_path}/Makefile")
    ["make"]
  else
    nil
  end.to_json
%>

name: npm-project
startup_window: <%= project_name %>
# XXX Don't reprompt for this when it's already added.
on_project_start: ssh-add ~/.ssh/id_rsa.bob

windows:
  - notes:
      root: <%= ENV.fetch('NOTES') %>
      layout: even-horizontal
      panes:
        - gpl
        - vim

  - <%= project_name %>:
      layout: '6827,274x73,0,0{136x73,0,0[136x36,0,0,41,136x36,0,37,50],137x73,137,0,47}'
      root: <%= project_path %>
      panes:
        - <%= project_specific_setup %>
        -
        - vim

  - dotfiles:
      root: <%= ENV.fetch('DOTFILES') %>
      layout: even-horizontal
      panes:
        - gpl
        - vim
