#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
dir="$(git rev-parse --git-dir)"

mkdir .git/tags_lock 2>/dev/null # || exit 0
trap 'rmdir .git/tags_lock; rm -f "$dir/$$.tags"' EXIT

git ls-files | \
  ctags --tag-relative='always' -L - -f"$dir/$$.tags"
mv "$dir/$$.tags" "$dir/tags"
