#!/bin/sh

# Run local hook if it exists
if [ -x ".git/hooks/post-rewrite" ]; then
    .git/hooks/post-rewrite "$@"
fi

case "$1" in
  rebase) exec ~/src/github.com/bobwhitelock/dotfiles/git/hooks/post-merge ;;
esac
