#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

# Fuzzy select repo from all cloned repos, then run given command on full path
# to repo.

main() {
    local command_to_run
    command_to_run="$1"
    shift

    find "$SRC" -mindepth 1 -type d -exec test -e "{}/.git" \; -print -prune | \
        sed "s%$SRC/%%" | \
        sort | \
        fzf --ansi --query="$*" | \
        _run_command_on_repo "$command_to_run"
}

_run_command_on_repo() {
    local repo command_to_run
    command_to_run="$1"

    repo="$(cat)"
    if [ -z "$repo" ]; then
        exit 1
    fi

    eval "$command_to_run" "$SRC/$repo"
}

main "$@"
