#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# Fuzzy select repo from all cloned repos, then open window for repo with
# provided command.

main() {
    local open_command
    open_command="$1"
    shift

    # shellcheck disable=SC2012
    ls "$SRC"/*/* -d1 --color=always | \
        # Drop $SRC prefix.
        sed "s%$SRC/%%" | \
        # Drop trailing slash.
        sed "s%/$%%" | \
        fzf --ansi --query="$*" | \
        _add_window "$open_command"
}

_add_window() {
    local repo open_command
    open_command="$1"

    repo="$(cat)"
    if [ -z "$repo" ]; then
        exit 1
    fi

    eval "$open_command" "$SRC/$repo"
}

main "$@"
