
export GITHUB_PASSWORD=XXX

export RESCALE_API_TOKEN_LOCALDEV=XXX
export RESCALE_API_TOKEN_DEV=XXX
export RESCALE_API_TOKEN_STAGE=XXX
export RESCALE_API_TOKEN_PROD=XXX

# For Rescale integration tests.
export UI_TEST_ACCOUNT_EMAIL=XXX
export UI_TEST_ACCOUNT_PASSWORD=XXX

export AWS_ACCESS_KEY_ID=XXX
export AWS_SECRET_ACCESS_KEY=XXX
export AWS_DEFAULT_REGION=XXX
