
#
# Personal
#

export GITHUB_PASSWORD=XXX

export GITHUB_CLI_TOKEN_PERSONAL=XXX
export GITHUB_CLI_TOKEN_RESCALE=XXX

export PUSHOVER_TOKEN=XXX
export PUSHOVER_USER=XXX

#
# Rescale
#

# Platform API keys; will also be aliased in
# `dotfiles-private/zsh/lib/rescale.sh` for different tools.
export RESCALE_API_TOKEN_LOCALDEV=XXX
export RESCALE_API_TOKEN_DEV=XXX
export RESCALE_API_TOKEN_STAGING=XXX
export JORF_APIKEY_PLATFORM_STAGE_RESCALE_COM="$RESCALE_API_TOKEN_STAGE"
export RESCALE_API_TOKEN_PROD=XXX
export RESCALE_API_TOKEN_DEPROD=XXX
export RESCALE_API_TOKEN_JPPROD=XXX
export RESCALE_API_TOKEN_KRPROD=XXX

export LOGDNA_KEY_DEV=XXX
export LOGDNA_KEY_STAGE=XXX
export LOGDNA_KEY_PROD=XXX

export ANCHORECTL_PASSWORD=XXX

export OKTA_API_TOKEN=XXX
